// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	polymarket "github.com/superform-xyz/superform-go-utils/providers/polymarket"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// CancelOrder provides a mock function with given fields: ctx, credentials, orderID
func (_m *MockClient) CancelOrder(ctx context.Context, credentials polymarket.Credentials, orderID string) (*polymarket.CancelResult, error) {
	ret := _m.Called(ctx, credentials, orderID)

	if len(ret) == 0 {
		panic("no return value specified for CancelOrder")
	}

	var r0 *polymarket.CancelResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, polymarket.Credentials, string) (*polymarket.CancelResult, error)); ok {
		return rf(ctx, credentials, orderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, polymarket.Credentials, string) *polymarket.CancelResult); ok {
		r0 = rf(ctx, credentials, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*polymarket.CancelResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, polymarket.Credentials, string) error); ok {
		r1 = rf(ctx, credentials, orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_CancelOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelOrder'
type MockClient_CancelOrder_Call struct {
	*mock.Call
}

// CancelOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - credentials polymarket.Credentials
//   - orderID string
func (_e *MockClient_Expecter) CancelOrder(ctx interface{}, credentials interface{}, orderID interface{}) *MockClient_CancelOrder_Call {
	return &MockClient_CancelOrder_Call{Call: _e.mock.On("CancelOrder", ctx, credentials, orderID)}
}

func (_c *MockClient_CancelOrder_Call) Run(run func(ctx context.Context, credentials polymarket.Credentials, orderID string)) *MockClient_CancelOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(polymarket.Credentials), args[2].(string))
	})
	return _c
}

func (_c *MockClient_CancelOrder_Call) Return(_a0 *polymarket.CancelResult, _a1 error) *MockClient_CancelOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_CancelOrder_Call) RunAndReturn(run func(context.Context, polymarket.Credentials, string) (*polymarket.CancelResult, error)) *MockClient_CancelOrder_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function with no fields
func (_m *MockClient) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockClient_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockClient_Expecter) Close() *MockClient_Close_Call {
	return &MockClient_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockClient_Close_Call) Run(run func()) *MockClient_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Close_Call) Return(_a0 error) *MockClient_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_Close_Call) RunAndReturn(run func() error) *MockClient_Close_Call {
	_c.Call.Return(run)
	return _c
}

// GetMarket provides a mock function with given fields: ctx, conditionID, includeBooks
func (_m *MockClient) GetMarket(ctx context.Context, conditionID string, includeBooks bool) (*polymarket.Market, error) {
	ret := _m.Called(ctx, conditionID, includeBooks)

	if len(ret) == 0 {
		panic("no return value specified for GetMarket")
	}

	var r0 *polymarket.Market
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) (*polymarket.Market, error)); ok {
		return rf(ctx, conditionID, includeBooks)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) *polymarket.Market); ok {
		r0 = rf(ctx, conditionID, includeBooks)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*polymarket.Market)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, bool) error); ok {
		r1 = rf(ctx, conditionID, includeBooks)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetMarket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMarket'
type MockClient_GetMarket_Call struct {
	*mock.Call
}

// GetMarket is a helper method to define mock.On call
//   - ctx context.Context
//   - conditionID string
//   - includeBooks bool
func (_e *MockClient_Expecter) GetMarket(ctx interface{}, conditionID interface{}, includeBooks interface{}) *MockClient_GetMarket_Call {
	return &MockClient_GetMarket_Call{Call: _e.mock.On("GetMarket", ctx, conditionID, includeBooks)}
}

func (_c *MockClient_GetMarket_Call) Run(run func(ctx context.Context, conditionID string, includeBooks bool)) *MockClient_GetMarket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(bool))
	})
	return _c
}

func (_c *MockClient_GetMarket_Call) Return(_a0 *polymarket.Market, _a1 error) *MockClient_GetMarket_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetMarket_Call) RunAndReturn(run func(context.Context, string, bool) (*polymarket.Market, error)) *MockClient_GetMarket_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrder provides a mock function with given fields: ctx, credentials, orderID
func (_m *MockClient) GetOrder(ctx context.Context, credentials polymarket.Credentials, orderID string) (*polymarket.OpenOrder, error) {
	ret := _m.Called(ctx, credentials, orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 *polymarket.OpenOrder
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, polymarket.Credentials, string) (*polymarket.OpenOrder, error)); ok {
		return rf(ctx, credentials, orderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, polymarket.Credentials, string) *polymarket.OpenOrder); ok {
		r0 = rf(ctx, credentials, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*polymarket.OpenOrder)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, polymarket.Credentials, string) error); ok {
		r1 = rf(ctx, credentials, orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type MockClient_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - credentials polymarket.Credentials
//   - orderID string
func (_e *MockClient_Expecter) GetOrder(ctx interface{}, credentials interface{}, orderID interface{}) *MockClient_GetOrder_Call {
	return &MockClient_GetOrder_Call{Call: _e.mock.On("GetOrder", ctx, credentials, orderID)}
}

func (_c *MockClient_GetOrder_Call) Run(run func(ctx context.Context, credentials polymarket.Credentials, orderID string)) *MockClient_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(polymarket.Credentials), args[2].(string))
	})
	return _c
}

func (_c *MockClient_GetOrder_Call) Return(_a0 *polymarket.OpenOrder, _a1 error) *MockClient_GetOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetOrder_Call) RunAndReturn(run func(context.Context, polymarket.Credentials, string) (*polymarket.OpenOrder, error)) *MockClient_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}

// ListMarkets provides a mock function with given fields: ctx, nextCursor
func (_m *MockClient) ListMarkets(ctx context.Context, nextCursor string) (*polymarket.MarketPage, error) {
	ret := _m.Called(ctx, nextCursor)

	if len(ret) == 0 {
		panic("no return value specified for ListMarkets")
	}

	var r0 *polymarket.MarketPage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*polymarket.MarketPage, error)); ok {
		return rf(ctx, nextCursor)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *polymarket.MarketPage); ok {
		r0 = rf(ctx, nextCursor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*polymarket.MarketPage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, nextCursor)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_ListMarkets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMarkets'
type MockClient_ListMarkets_Call struct {
	*mock.Call
}

// ListMarkets is a helper method to define mock.On call
//   - ctx context.Context
//   - nextCursor string
func (_e *MockClient_Expecter) ListMarkets(ctx interface{}, nextCursor interface{}) *MockClient_ListMarkets_Call {
	return &MockClient_ListMarkets_Call{Call: _e.mock.On("ListMarkets", ctx, nextCursor)}
}

func (_c *MockClient_ListMarkets_Call) Run(run func(ctx context.Context, nextCursor string)) *MockClient_ListMarkets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClient_ListMarkets_Call) Return(_a0 *polymarket.MarketPage, _a1 error) *MockClient_ListMarkets_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_ListMarkets_Call) RunAndReturn(run func(context.Context, string) (*polymarket.MarketPage, error)) *MockClient_ListMarkets_Call {
	_c.Call.Return(run)
	return _c
}

// ListOpenOrders provides a mock function with given fields: ctx, credentials, filter
func (_m *MockClient) ListOpenOrders(ctx context.Context, credentials polymarket.Credentials, filter polymarket.OpenOrderFilter) (*polymarket.OpenOrderPage, error) {
	ret := _m.Called(ctx, credentials, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListOpenOrders")
	}

	var r0 *polymarket.OpenOrderPage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, polymarket.Credentials, polymarket.OpenOrderFilter) (*polymarket.OpenOrderPage, error)); ok {
		return rf(ctx, credentials, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, polymarket.Credentials, polymarket.OpenOrderFilter) *polymarket.OpenOrderPage); ok {
		r0 = rf(ctx, credentials, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*polymarket.OpenOrderPage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, polymarket.Credentials, polymarket.OpenOrderFilter) error); ok {
		r1 = rf(ctx, credentials, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_ListOpenOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListOpenOrders'
type MockClient_ListOpenOrders_Call struct {
	*mock.Call
}

// ListOpenOrders is a helper method to define mock.On call
//   - ctx context.Context
//   - credentials polymarket.Credentials
//   - filter polymarket.OpenOrderFilter
func (_e *MockClient_Expecter) ListOpenOrders(ctx interface{}, credentials interface{}, filter interface{}) *MockClient_ListOpenOrders_Call {
	return &MockClient_ListOpenOrders_Call{Call: _e.mock.On("ListOpenOrders", ctx, credentials, filter)}
}

func (_c *MockClient_ListOpenOrders_Call) Run(run func(ctx context.Context, credentials polymarket.Credentials, filter polymarket.OpenOrderFilter)) *MockClient_ListOpenOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(polymarket.Credentials), args[2].(polymarket.OpenOrderFilter))
	})
	return _c
}

func (_c *MockClient_ListOpenOrders_Call) Return(_a0 *polymarket.OpenOrderPage, _a1 error) *MockClient_ListOpenOrders_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_ListOpenOrders_Call) RunAndReturn(run func(context.Context, polymarket.Credentials, polymarket.OpenOrderFilter) (*polymarket.OpenOrderPage, error)) *MockClient_ListOpenOrders_Call {
	_c.Call.Return(run)
	return _c
}

// PostOrder provides a mock function with given fields: ctx, credentials, order
func (_m *MockClient) PostOrder(ctx context.Context, credentials polymarket.Credentials, order polymarket.SignedOrder) (*polymarket.OrderPlacement, error) {
	ret := _m.Called(ctx, credentials, order)

	if len(ret) == 0 {
		panic("no return value specified for PostOrder")
	}

	var r0 *polymarket.OrderPlacement
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, polymarket.Credentials, polymarket.SignedOrder) (*polymarket.OrderPlacement, error)); ok {
		return rf(ctx, credentials, order)
	}
	if rf, ok := ret.Get(0).(func(context.Context, polymarket.Credentials, polymarket.SignedOrder) *polymarket.OrderPlacement); ok {
		r0 = rf(ctx, credentials, order)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*polymarket.OrderPlacement)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, polymarket.Credentials, polymarket.SignedOrder) error); ok {
		r1 = rf(ctx, credentials, order)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_PostOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostOrder'
type MockClient_PostOrder_Call struct {
	*mock.Call
}

// PostOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - credentials polymarket.Credentials
//   - order polymarket.SignedOrder
func (_e *MockClient_Expecter) PostOrder(ctx interface{}, credentials interface{}, order interface{}) *MockClient_PostOrder_Call {
	return &MockClient_PostOrder_Call{Call: _e.mock.On("PostOrder", ctx, credentials, order)}
}

func (_c *MockClient_PostOrder_Call) Run(run func(ctx context.Context, credentials polymarket.Credentials, order polymarket.SignedOrder)) *MockClient_PostOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(polymarket.Credentials), args[2].(polymarket.SignedOrder))
	})
	return _c
}

func (_c *MockClient_PostOrder_Call) Return(_a0 *polymarket.OrderPlacement, _a1 error) *MockClient_PostOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_PostOrder_Call) RunAndReturn(run func(context.Context, polymarket.Credentials, polymarket.SignedOrder) (*polymarket.OrderPlacement, error)) *MockClient_PostOrder_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBalanceAllowance provides a mock function with given fields: ctx, credentials, update
func (_m *MockClient) UpdateBalanceAllowance(ctx context.Context, credentials polymarket.Credentials, update polymarket.BalanceAllowanceUpdate) error {
	ret := _m.Called(ctx, credentials, update)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBalanceAllowance")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, polymarket.Credentials, polymarket.BalanceAllowanceUpdate) error); ok {
		r0 = rf(ctx, credentials, update)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_UpdateBalanceAllowance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBalanceAllowance'
type MockClient_UpdateBalanceAllowance_Call struct {
	*mock.Call
}

// UpdateBalanceAllowance is a helper method to define mock.On call
//   - ctx context.Context
//   - credentials polymarket.Credentials
//   - update polymarket.BalanceAllowanceUpdate
func (_e *MockClient_Expecter) UpdateBalanceAllowance(ctx interface{}, credentials interface{}, update interface{}) *MockClient_UpdateBalanceAllowance_Call {
	return &MockClient_UpdateBalanceAllowance_Call{Call: _e.mock.On("UpdateBalanceAllowance", ctx, credentials, update)}
}

func (_c *MockClient_UpdateBalanceAllowance_Call) Run(run func(ctx context.Context, credentials polymarket.Credentials, update polymarket.BalanceAllowanceUpdate)) *MockClient_UpdateBalanceAllowance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(polymarket.Credentials), args[2].(polymarket.BalanceAllowanceUpdate))
	})
	return _c
}

func (_c *MockClient_UpdateBalanceAllowance_Call) Return(_a0 error) *MockClient_UpdateBalanceAllowance_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_UpdateBalanceAllowance_Call) RunAndReturn(run func(context.Context, polymarket.Credentials, polymarket.BalanceAllowanceUpdate) error) *MockClient_UpdateBalanceAllowance_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
