// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	rhinestone "github.com/superform-xyz/superform-go-utils/providers/rhinestone"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockClient) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockClient_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockClient_Expecter) Close() *MockClient_Close_Call {
	return &MockClient_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockClient_Close_Call) Run(run func()) *MockClient_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Close_Call) Return(_a0 error) *MockClient_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_Close_Call) RunAndReturn(run func() error) *MockClient_Close_Call {
	_c.Call.Return(run)
	return _c
}

// GetChains provides a mock function with given fields: _a0
func (_m *MockClient) GetChains(_a0 context.Context) (map[string]rhinestone.Chain, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetChains")
	}

	var r0 map[string]rhinestone.Chain
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (map[string]rhinestone.Chain, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) map[string]rhinestone.Chain); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]rhinestone.Chain)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetChains_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChains'
type MockClient_GetChains_Call struct {
	*mock.Call
}

// GetChains is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockClient_Expecter) GetChains(_a0 interface{}) *MockClient_GetChains_Call {
	return &MockClient_GetChains_Call{Call: _e.mock.On("GetChains", _a0)}
}

func (_c *MockClient_GetChains_Call) Run(run func(_a0 context.Context)) *MockClient_GetChains_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockClient_GetChains_Call) Return(_a0 map[string]rhinestone.Chain, _a1 error) *MockClient_GetChains_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetChains_Call) RunAndReturn(run func(context.Context) (map[string]rhinestone.Chain, error)) *MockClient_GetChains_Call {
	_c.Call.Return(run)
	return _c
}

// GetOnrampOptions provides a mock function with given fields: _a0, _a1
func (_m *MockClient) GetOnrampOptions(_a0 context.Context, _a1 rhinestone.GetOnrampOptionsRequest) (*rhinestone.GetOnrampOptionsResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetOnrampOptions")
	}

	var r0 *rhinestone.GetOnrampOptionsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, rhinestone.GetOnrampOptionsRequest) (*rhinestone.GetOnrampOptionsResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, rhinestone.GetOnrampOptionsRequest) *rhinestone.GetOnrampOptionsResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rhinestone.GetOnrampOptionsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, rhinestone.GetOnrampOptionsRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetOnrampOptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOnrampOptions'
type MockClient_GetOnrampOptions_Call struct {
	*mock.Call
}

// GetOnrampOptions is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 rhinestone.GetOnrampOptionsRequest
func (_e *MockClient_Expecter) GetOnrampOptions(_a0 interface{}, _a1 interface{}) *MockClient_GetOnrampOptions_Call {
	return &MockClient_GetOnrampOptions_Call{Call: _e.mock.On("GetOnrampOptions", _a0, _a1)}
}

func (_c *MockClient_GetOnrampOptions_Call) Run(run func(_a0 context.Context, _a1 rhinestone.GetOnrampOptionsRequest)) *MockClient_GetOnrampOptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(rhinestone.GetOnrampOptionsRequest))
	})
	return _c
}

func (_c *MockClient_GetOnrampOptions_Call) Return(_a0 *rhinestone.GetOnrampOptionsResponse, _a1 error) *MockClient_GetOnrampOptions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetOnrampOptions_Call) RunAndReturn(run func(context.Context, rhinestone.GetOnrampOptionsRequest) (*rhinestone.GetOnrampOptionsResponse, error)) *MockClient_GetOnrampOptions_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
