// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	openocean "github.com/superform-xyz/superform-go-utils/providers/openocean"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockClient) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockClient_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockClient_Expecter) Close() *MockClient_Close_Call {
	return &MockClient_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockClient_Close_Call) Run(run func()) *MockClient_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Close_Call) Return(_a0 error) *MockClient_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_Close_Call) RunAndReturn(run func() error) *MockClient_Close_Call {
	_c.Call.Return(run)
	return _c
}

// GetSwap provides a mock function with given fields: ctx, req
func (_m *MockClient) GetSwap(ctx context.Context, req openocean.SwapRequest) (*openocean.Swap, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetSwap")
	}

	var r0 *openocean.Swap
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, openocean.SwapRequest) (*openocean.Swap, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, openocean.SwapRequest) *openocean.Swap); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*openocean.Swap)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, openocean.SwapRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetSwap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSwap'
type MockClient_GetSwap_Call struct {
	*mock.Call
}

// GetSwap is a helper method to define mock.On call
//   - ctx context.Context
//   - req openocean.SwapRequest
func (_e *MockClient_Expecter) GetSwap(ctx interface{}, req interface{}) *MockClient_GetSwap_Call {
	return &MockClient_GetSwap_Call{Call: _e.mock.On("GetSwap", ctx, req)}
}

func (_c *MockClient_GetSwap_Call) Run(run func(ctx context.Context, req openocean.SwapRequest)) *MockClient_GetSwap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(openocean.SwapRequest))
	})
	return _c
}

func (_c *MockClient_GetSwap_Call) Return(_a0 *openocean.Swap, _a1 error) *MockClient_GetSwap_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetSwap_Call) RunAndReturn(run func(context.Context, openocean.SwapRequest) (*openocean.Swap, error)) *MockClient_GetSwap_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
