// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	kyberswap "github.com/superform-xyz/superform-go-utils/providers/kyberswap"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// BuildRoute provides a mock function with given fields: ctx, req
func (_m *MockClient) BuildRoute(ctx context.Context, req kyberswap.BuildRequest) (*kyberswap.Build, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for BuildRoute")
	}

	var r0 *kyberswap.Build
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, kyberswap.BuildRequest) (*kyberswap.Build, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, kyberswap.BuildRequest) *kyberswap.Build); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*kyberswap.Build)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, kyberswap.BuildRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_BuildRoute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuildRoute'
type MockClient_BuildRoute_Call struct {
	*mock.Call
}

// BuildRoute is a helper method to define mock.On call
//   - ctx context.Context
//   - req kyberswap.BuildRequest
func (_e *MockClient_Expecter) BuildRoute(ctx interface{}, req interface{}) *MockClient_BuildRoute_Call {
	return &MockClient_BuildRoute_Call{Call: _e.mock.On("BuildRoute", ctx, req)}
}

func (_c *MockClient_BuildRoute_Call) Run(run func(ctx context.Context, req kyberswap.BuildRequest)) *MockClient_BuildRoute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(kyberswap.BuildRequest))
	})
	return _c
}

func (_c *MockClient_BuildRoute_Call) Return(_a0 *kyberswap.Build, _a1 error) *MockClient_BuildRoute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_BuildRoute_Call) RunAndReturn(run func(context.Context, kyberswap.BuildRequest) (*kyberswap.Build, error)) *MockClient_BuildRoute_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function with no fields
func (_m *MockClient) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockClient_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockClient_Expecter) Close() *MockClient_Close_Call {
	return &MockClient_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockClient_Close_Call) Run(run func()) *MockClient_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Close_Call) Return(_a0 error) *MockClient_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_Close_Call) RunAndReturn(run func() error) *MockClient_Close_Call {
	_c.Call.Return(run)
	return _c
}

// GetRoute provides a mock function with given fields: ctx, req
func (_m *MockClient) GetRoute(ctx context.Context, req kyberswap.RouteRequest) (*kyberswap.Route, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetRoute")
	}

	var r0 *kyberswap.Route
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, kyberswap.RouteRequest) (*kyberswap.Route, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, kyberswap.RouteRequest) *kyberswap.Route); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*kyberswap.Route)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, kyberswap.RouteRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetRoute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoute'
type MockClient_GetRoute_Call struct {
	*mock.Call
}

// GetRoute is a helper method to define mock.On call
//   - ctx context.Context
//   - req kyberswap.RouteRequest
func (_e *MockClient_Expecter) GetRoute(ctx interface{}, req interface{}) *MockClient_GetRoute_Call {
	return &MockClient_GetRoute_Call{Call: _e.mock.On("GetRoute", ctx, req)}
}

func (_c *MockClient_GetRoute_Call) Run(run func(ctx context.Context, req kyberswap.RouteRequest)) *MockClient_GetRoute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(kyberswap.RouteRequest))
	})
	return _c
}

func (_c *MockClient_GetRoute_Call) Return(_a0 *kyberswap.Route, _a1 error) *MockClient_GetRoute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetRoute_Call) RunAndReturn(run func(context.Context, kyberswap.RouteRequest) (*kyberswap.Route, error)) *MockClient_GetRoute_Call {
	_c.Call.Return(run)
	return _c
}

// SupportedChains provides a mock function with no fields
func (_m *MockClient) SupportedChains() []uint64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SupportedChains")
	}

	var r0 []uint64
	if rf, ok := ret.Get(0).(func() []uint64); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uint64)
		}
	}

	return r0
}

// MockClient_SupportedChains_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SupportedChains'
type MockClient_SupportedChains_Call struct {
	*mock.Call
}

// SupportedChains is a helper method to define mock.On call
func (_e *MockClient_Expecter) SupportedChains() *MockClient_SupportedChains_Call {
	return &MockClient_SupportedChains_Call{Call: _e.mock.On("SupportedChains")}
}

func (_c *MockClient_SupportedChains_Call) Run(run func()) *MockClient_SupportedChains_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_SupportedChains_Call) Return(_a0 []uint64) *MockClient_SupportedChains_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_SupportedChains_Call) RunAndReturn(run func() []uint64) *MockClient_SupportedChains_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
