// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	zerion "github.com/superform-xyz/superform-go-utils/providers/zerion"
)

// MockZerion is an autogenerated mock type for the Zerion type
type MockZerion struct {
	mock.Mock
}

type MockZerion_Expecter struct {
	mock *mock.Mock
}

func (_m *MockZerion) EXPECT() *MockZerion_Expecter {
	return &MockZerion_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockZerion) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockZerion_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockZerion_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockZerion_Expecter) Close() *MockZerion_Close_Call {
	return &MockZerion_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockZerion_Close_Call) Run(run func()) *MockZerion_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockZerion_Close_Call) Return(_a0 error) *MockZerion_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockZerion_Close_Call) RunAndReturn(run func() error) *MockZerion_Close_Call {
	_c.Call.Return(run)
	return _c
}

// GetWalletPositions provides a mock function with given fields: ctx, address, req
func (_m *MockZerion) GetWalletPositions(ctx context.Context, address string, req zerion.WalletPositionsRequest) ([]zerion.Position, error) {
	ret := _m.Called(ctx, address, req)

	if len(ret) == 0 {
		panic("no return value specified for GetWalletPositions")
	}

	var r0 []zerion.Position
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, zerion.WalletPositionsRequest) ([]zerion.Position, error)); ok {
		return rf(ctx, address, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, zerion.WalletPositionsRequest) []zerion.Position); ok {
		r0 = rf(ctx, address, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]zerion.Position)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, zerion.WalletPositionsRequest) error); ok {
		r1 = rf(ctx, address, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockZerion_GetWalletPositions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWalletPositions'
type MockZerion_GetWalletPositions_Call struct {
	*mock.Call
}

// GetWalletPositions is a helper method to define mock.On call
//   - ctx context.Context
//   - address string
//   - req zerion.WalletPositionsRequest
func (_e *MockZerion_Expecter) GetWalletPositions(ctx interface{}, address interface{}, req interface{}) *MockZerion_GetWalletPositions_Call {
	return &MockZerion_GetWalletPositions_Call{Call: _e.mock.On("GetWalletPositions", ctx, address, req)}
}

func (_c *MockZerion_GetWalletPositions_Call) Run(run func(ctx context.Context, address string, req zerion.WalletPositionsRequest)) *MockZerion_GetWalletPositions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(zerion.WalletPositionsRequest))
	})
	return _c
}

func (_c *MockZerion_GetWalletPositions_Call) Return(_a0 []zerion.Position, _a1 error) *MockZerion_GetWalletPositions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockZerion_GetWalletPositions_Call) RunAndReturn(run func(context.Context, string, zerion.WalletPositionsRequest) ([]zerion.Position, error)) *MockZerion_GetWalletPositions_Call {
	_c.Call.Return(run)
	return _c
}

// HealthCheck provides a mock function with given fields: ctx
func (_m *MockZerion) HealthCheck(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for HealthCheck")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockZerion_HealthCheck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HealthCheck'
type MockZerion_HealthCheck_Call struct {
	*mock.Call
}

// HealthCheck is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockZerion_Expecter) HealthCheck(ctx interface{}) *MockZerion_HealthCheck_Call {
	return &MockZerion_HealthCheck_Call{Call: _e.mock.On("HealthCheck", ctx)}
}

func (_c *MockZerion_HealthCheck_Call) Run(run func(ctx context.Context)) *MockZerion_HealthCheck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockZerion_HealthCheck_Call) Return(_a0 error) *MockZerion_HealthCheck_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockZerion_HealthCheck_Call) RunAndReturn(run func(context.Context) error) *MockZerion_HealthCheck_Call {
	_c.Call.Return(run)
	return _c
}

// SupportedChains provides a mock function with no fields
func (_m *MockZerion) SupportedChains() []uint64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SupportedChains")
	}

	var r0 []uint64
	if rf, ok := ret.Get(0).(func() []uint64); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uint64)
		}
	}

	return r0
}

// MockZerion_SupportedChains_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SupportedChains'
type MockZerion_SupportedChains_Call struct {
	*mock.Call
}

// SupportedChains is a helper method to define mock.On call
func (_e *MockZerion_Expecter) SupportedChains() *MockZerion_SupportedChains_Call {
	return &MockZerion_SupportedChains_Call{Call: _e.mock.On("SupportedChains")}
}

func (_c *MockZerion_SupportedChains_Call) Run(run func()) *MockZerion_SupportedChains_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockZerion_SupportedChains_Call) Return(_a0 []uint64) *MockZerion_SupportedChains_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockZerion_SupportedChains_Call) RunAndReturn(run func() []uint64) *MockZerion_SupportedChains_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockZerion creates a new instance of MockZerion. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockZerion(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockZerion {
	mock := &MockZerion{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
