// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	odos "github.com/superform-xyz/superform-go-utils/providers/odos"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// Assemble provides a mock function with given fields: ctx, req
func (_m *MockClient) Assemble(ctx context.Context, req odos.AssembleRequest) (*odos.Assemble, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Assemble")
	}

	var r0 *odos.Assemble
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, odos.AssembleRequest) (*odos.Assemble, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, odos.AssembleRequest) *odos.Assemble); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*odos.Assemble)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, odos.AssembleRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_Assemble_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Assemble'
type MockClient_Assemble_Call struct {
	*mock.Call
}

// Assemble is a helper method to define mock.On call
//   - ctx context.Context
//   - req odos.AssembleRequest
func (_e *MockClient_Expecter) Assemble(ctx interface{}, req interface{}) *MockClient_Assemble_Call {
	return &MockClient_Assemble_Call{Call: _e.mock.On("Assemble", ctx, req)}
}

func (_c *MockClient_Assemble_Call) Run(run func(ctx context.Context, req odos.AssembleRequest)) *MockClient_Assemble_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(odos.AssembleRequest))
	})
	return _c
}

func (_c *MockClient_Assemble_Call) Return(_a0 *odos.Assemble, _a1 error) *MockClient_Assemble_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_Assemble_Call) RunAndReturn(run func(context.Context, odos.AssembleRequest) (*odos.Assemble, error)) *MockClient_Assemble_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function with no fields
func (_m *MockClient) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockClient_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockClient_Expecter) Close() *MockClient_Close_Call {
	return &MockClient_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockClient_Close_Call) Run(run func()) *MockClient_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Close_Call) Return(_a0 error) *MockClient_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_Close_Call) RunAndReturn(run func() error) *MockClient_Close_Call {
	_c.Call.Return(run)
	return _c
}

// GetQuote provides a mock function with given fields: ctx, req
func (_m *MockClient) GetQuote(ctx context.Context, req odos.QuoteRequest) (*odos.Quote, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetQuote")
	}

	var r0 *odos.Quote
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, odos.QuoteRequest) (*odos.Quote, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, odos.QuoteRequest) *odos.Quote); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*odos.Quote)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, odos.QuoteRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetQuote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQuote'
type MockClient_GetQuote_Call struct {
	*mock.Call
}

// GetQuote is a helper method to define mock.On call
//   - ctx context.Context
//   - req odos.QuoteRequest
func (_e *MockClient_Expecter) GetQuote(ctx interface{}, req interface{}) *MockClient_GetQuote_Call {
	return &MockClient_GetQuote_Call{Call: _e.mock.On("GetQuote", ctx, req)}
}

func (_c *MockClient_GetQuote_Call) Run(run func(ctx context.Context, req odos.QuoteRequest)) *MockClient_GetQuote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(odos.QuoteRequest))
	})
	return _c
}

func (_c *MockClient_GetQuote_Call) Return(_a0 *odos.Quote, _a1 error) *MockClient_GetQuote_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetQuote_Call) RunAndReturn(run func(context.Context, odos.QuoteRequest) (*odos.Quote, error)) *MockClient_GetQuote_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
