// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
	http_client "github.com/superform-xyz/superform-go-utils/pkg/http_client"

	time "time"
)

// MockClientBuilder is an autogenerated mock type for the ClientBuilder type
type MockClientBuilder struct {
	mock.Mock
}

type MockClientBuilder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientBuilder) EXPECT() *MockClientBuilder_Expecter {
	return &MockClientBuilder_Expecter{mock: &_m.Mock}
}

// BuildClient provides a mock function with no fields
func (_m *MockClientBuilder) BuildClient() *http_client.Client {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for BuildClient")
	}

	var r0 *http_client.Client
	if rf, ok := ret.Get(0).(func() *http_client.Client); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http_client.Client)
		}
	}

	return r0
}

// MockClientBuilder_BuildClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuildClient'
type MockClientBuilder_BuildClient_Call struct {
	*mock.Call
}

// BuildClient is a helper method to define mock.On call
func (_e *MockClientBuilder_Expecter) BuildClient() *MockClientBuilder_BuildClient_Call {
	return &MockClientBuilder_BuildClient_Call{Call: _e.mock.On("BuildClient")}
}

func (_c *MockClientBuilder_BuildClient_Call) Run(run func()) *MockClientBuilder_BuildClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientBuilder_BuildClient_Call) Return(_a0 *http_client.Client) *MockClientBuilder_BuildClient_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClientBuilder_BuildClient_Call) RunAndReturn(run func() *http_client.Client) *MockClientBuilder_BuildClient_Call {
	_c.Call.Return(run)
	return _c
}

// SetAuth provides a mock function with given fields: key, value
func (_m *MockClientBuilder) SetAuth(key string, value string) http_client.ClientBuilder {
	ret := _m.Called(key, value)

	if len(ret) == 0 {
		panic("no return value specified for SetAuth")
	}

	var r0 http_client.ClientBuilder
	if rf, ok := ret.Get(0).(func(string, string) http_client.ClientBuilder); ok {
		r0 = rf(key, value)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http_client.ClientBuilder)
		}
	}

	return r0
}

// MockClientBuilder_SetAuth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAuth'
type MockClientBuilder_SetAuth_Call struct {
	*mock.Call
}

// SetAuth is a helper method to define mock.On call
//   - key string
//   - value string
func (_e *MockClientBuilder_Expecter) SetAuth(key interface{}, value interface{}) *MockClientBuilder_SetAuth_Call {
	return &MockClientBuilder_SetAuth_Call{Call: _e.mock.On("SetAuth", key, value)}
}

func (_c *MockClientBuilder_SetAuth_Call) Run(run func(key string, value string)) *MockClientBuilder_SetAuth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockClientBuilder_SetAuth_Call) Return(_a0 http_client.ClientBuilder) *MockClientBuilder_SetAuth_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClientBuilder_SetAuth_Call) RunAndReturn(run func(string, string) http_client.ClientBuilder) *MockClientBuilder_SetAuth_Call {
	_c.Call.Return(run)
	return _c
}

// SetRetry provides a mock function with given fields: maxRetries, retryDelay
func (_m *MockClientBuilder) SetRetry(maxRetries uint, retryDelay time.Duration) http_client.ClientBuilder {
	ret := _m.Called(maxRetries, retryDelay)

	if len(ret) == 0 {
		panic("no return value specified for SetRetry")
	}

	var r0 http_client.ClientBuilder
	if rf, ok := ret.Get(0).(func(uint, time.Duration) http_client.ClientBuilder); ok {
		r0 = rf(maxRetries, retryDelay)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http_client.ClientBuilder)
		}
	}

	return r0
}

// MockClientBuilder_SetRetry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetRetry'
type MockClientBuilder_SetRetry_Call struct {
	*mock.Call
}

// SetRetry is a helper method to define mock.On call
//   - maxRetries uint
//   - retryDelay time.Duration
func (_e *MockClientBuilder_Expecter) SetRetry(maxRetries interface{}, retryDelay interface{}) *MockClientBuilder_SetRetry_Call {
	return &MockClientBuilder_SetRetry_Call{Call: _e.mock.On("SetRetry", maxRetries, retryDelay)}
}

func (_c *MockClientBuilder_SetRetry_Call) Run(run func(maxRetries uint, retryDelay time.Duration)) *MockClientBuilder_SetRetry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint), args[1].(time.Duration))
	})
	return _c
}

func (_c *MockClientBuilder_SetRetry_Call) Return(_a0 http_client.ClientBuilder) *MockClientBuilder_SetRetry_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClientBuilder_SetRetry_Call) RunAndReturn(run func(uint, time.Duration) http_client.ClientBuilder) *MockClientBuilder_SetRetry_Call {
	_c.Call.Return(run)
	return _c
}

// SetTimeout provides a mock function with given fields: timeout
func (_m *MockClientBuilder) SetTimeout(timeout time.Duration) http_client.ClientBuilder {
	ret := _m.Called(timeout)

	if len(ret) == 0 {
		panic("no return value specified for SetTimeout")
	}

	var r0 http_client.ClientBuilder
	if rf, ok := ret.Get(0).(func(time.Duration) http_client.ClientBuilder); ok {
		r0 = rf(timeout)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http_client.ClientBuilder)
		}
	}

	return r0
}

// MockClientBuilder_SetTimeout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTimeout'
type MockClientBuilder_SetTimeout_Call struct {
	*mock.Call
}

// SetTimeout is a helper method to define mock.On call
//   - timeout time.Duration
func (_e *MockClientBuilder_Expecter) SetTimeout(timeout interface{}) *MockClientBuilder_SetTimeout_Call {
	return &MockClientBuilder_SetTimeout_Call{Call: _e.mock.On("SetTimeout", timeout)}
}

func (_c *MockClientBuilder_SetTimeout_Call) Run(run func(timeout time.Duration)) *MockClientBuilder_SetTimeout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(time.Duration))
	})
	return _c
}

func (_c *MockClientBuilder_SetTimeout_Call) Return(_a0 http_client.ClientBuilder) *MockClientBuilder_SetTimeout_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClientBuilder_SetTimeout_Call) RunAndReturn(run func(time.Duration) http_client.ClientBuilder) *MockClientBuilder_SetTimeout_Call {
	_c.Call.Return(run)
	return _c
}

// SetTransportWrapper provides a mock function with given fields: wrapper
func (_m *MockClientBuilder) SetTransportWrapper(wrapper func(http.RoundTripper) http.RoundTripper) http_client.ClientBuilder {
	ret := _m.Called(wrapper)

	if len(ret) == 0 {
		panic("no return value specified for SetTransportWrapper")
	}

	var r0 http_client.ClientBuilder
	if rf, ok := ret.Get(0).(func(func(http.RoundTripper) http.RoundTripper) http_client.ClientBuilder); ok {
		r0 = rf(wrapper)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http_client.ClientBuilder)
		}
	}

	return r0
}

// MockClientBuilder_SetTransportWrapper_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTransportWrapper'
type MockClientBuilder_SetTransportWrapper_Call struct {
	*mock.Call
}

// SetTransportWrapper is a helper method to define mock.On call
//   - wrapper func(http.RoundTripper) http.RoundTripper
func (_e *MockClientBuilder_Expecter) SetTransportWrapper(wrapper interface{}) *MockClientBuilder_SetTransportWrapper_Call {
	return &MockClientBuilder_SetTransportWrapper_Call{Call: _e.mock.On("SetTransportWrapper", wrapper)}
}

func (_c *MockClientBuilder_SetTransportWrapper_Call) Run(run func(wrapper func(http.RoundTripper) http.RoundTripper)) *MockClientBuilder_SetTransportWrapper_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(func(http.RoundTripper) http.RoundTripper))
	})
	return _c
}

func (_c *MockClientBuilder_SetTransportWrapper_Call) Return(_a0 http_client.ClientBuilder) *MockClientBuilder_SetTransportWrapper_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClientBuilder_SetTransportWrapper_Call) RunAndReturn(run func(func(http.RoundTripper) http.RoundTripper) http_client.ClientBuilder) *MockClientBuilder_SetTransportWrapper_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClientBuilder creates a new instance of MockClientBuilder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientBuilder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientBuilder {
	mock := &MockClientBuilder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
