// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	finnhub "github.com/superform-xyz/superform-go-utils/providers/finnhub"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockClient) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockClient_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockClient_Expecter) Close() *MockClient_Close_Call {
	return &MockClient_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockClient_Close_Call) Run(run func()) *MockClient_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Close_Call) Return(_a0 error) *MockClient_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_Close_Call) RunAndReturn(run func() error) *MockClient_Close_Call {
	_c.Call.Return(run)
	return _c
}

// GetCompanyBasicFinancials provides a mock function with given fields: ctx, req
func (_m *MockClient) GetCompanyBasicFinancials(ctx context.Context, req finnhub.BasicFinancialsRequest) (*finnhub.BasicFinancials, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetCompanyBasicFinancials")
	}

	var r0 *finnhub.BasicFinancials
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, finnhub.BasicFinancialsRequest) (*finnhub.BasicFinancials, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, finnhub.BasicFinancialsRequest) *finnhub.BasicFinancials); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*finnhub.BasicFinancials)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, finnhub.BasicFinancialsRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetCompanyBasicFinancials_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCompanyBasicFinancials'
type MockClient_GetCompanyBasicFinancials_Call struct {
	*mock.Call
}

// GetCompanyBasicFinancials is a helper method to define mock.On call
//   - ctx context.Context
//   - req finnhub.BasicFinancialsRequest
func (_e *MockClient_Expecter) GetCompanyBasicFinancials(ctx interface{}, req interface{}) *MockClient_GetCompanyBasicFinancials_Call {
	return &MockClient_GetCompanyBasicFinancials_Call{Call: _e.mock.On("GetCompanyBasicFinancials", ctx, req)}
}

func (_c *MockClient_GetCompanyBasicFinancials_Call) Run(run func(ctx context.Context, req finnhub.BasicFinancialsRequest)) *MockClient_GetCompanyBasicFinancials_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(finnhub.BasicFinancialsRequest))
	})
	return _c
}

func (_c *MockClient_GetCompanyBasicFinancials_Call) Return(_a0 *finnhub.BasicFinancials, _a1 error) *MockClient_GetCompanyBasicFinancials_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetCompanyBasicFinancials_Call) RunAndReturn(run func(context.Context, finnhub.BasicFinancialsRequest) (*finnhub.BasicFinancials, error)) *MockClient_GetCompanyBasicFinancials_Call {
	_c.Call.Return(run)
	return _c
}

// GetCompanyProfile provides a mock function with given fields: ctx, symbol
func (_m *MockClient) GetCompanyProfile(ctx context.Context, symbol string) (*finnhub.CompanyProfile, error) {
	ret := _m.Called(ctx, symbol)

	if len(ret) == 0 {
		panic("no return value specified for GetCompanyProfile")
	}

	var r0 *finnhub.CompanyProfile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*finnhub.CompanyProfile, error)); ok {
		return rf(ctx, symbol)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *finnhub.CompanyProfile); ok {
		r0 = rf(ctx, symbol)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*finnhub.CompanyProfile)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, symbol)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetCompanyProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCompanyProfile'
type MockClient_GetCompanyProfile_Call struct {
	*mock.Call
}

// GetCompanyProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - symbol string
func (_e *MockClient_Expecter) GetCompanyProfile(ctx interface{}, symbol interface{}) *MockClient_GetCompanyProfile_Call {
	return &MockClient_GetCompanyProfile_Call{Call: _e.mock.On("GetCompanyProfile", ctx, symbol)}
}

func (_c *MockClient_GetCompanyProfile_Call) Run(run func(ctx context.Context, symbol string)) *MockClient_GetCompanyProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClient_GetCompanyProfile_Call) Return(_a0 *finnhub.CompanyProfile, _a1 error) *MockClient_GetCompanyProfile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetCompanyProfile_Call) RunAndReturn(run func(context.Context, string) (*finnhub.CompanyProfile, error)) *MockClient_GetCompanyProfile_Call {
	_c.Call.Return(run)
	return _c
}

// GetStockFundamentals provides a mock function with given fields: ctx, symbol
func (_m *MockClient) GetStockFundamentals(ctx context.Context, symbol string) (*finnhub.StockFundamentals, error) {
	ret := _m.Called(ctx, symbol)

	if len(ret) == 0 {
		panic("no return value specified for GetStockFundamentals")
	}

	var r0 *finnhub.StockFundamentals
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*finnhub.StockFundamentals, error)); ok {
		return rf(ctx, symbol)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *finnhub.StockFundamentals); ok {
		r0 = rf(ctx, symbol)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*finnhub.StockFundamentals)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, symbol)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetStockFundamentals_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStockFundamentals'
type MockClient_GetStockFundamentals_Call struct {
	*mock.Call
}

// GetStockFundamentals is a helper method to define mock.On call
//   - ctx context.Context
//   - symbol string
func (_e *MockClient_Expecter) GetStockFundamentals(ctx interface{}, symbol interface{}) *MockClient_GetStockFundamentals_Call {
	return &MockClient_GetStockFundamentals_Call{Call: _e.mock.On("GetStockFundamentals", ctx, symbol)}
}

func (_c *MockClient_GetStockFundamentals_Call) Run(run func(ctx context.Context, symbol string)) *MockClient_GetStockFundamentals_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClient_GetStockFundamentals_Call) Return(_a0 *finnhub.StockFundamentals, _a1 error) *MockClient_GetStockFundamentals_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetStockFundamentals_Call) RunAndReturn(run func(context.Context, string) (*finnhub.StockFundamentals, error)) *MockClient_GetStockFundamentals_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
