// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	robinhood "github.com/superform-xyz/superform-go-utils/providers/robinhood"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// BuildConnectURL provides a mock function with given fields: req
func (_m *MockClient) BuildConnectURL(req robinhood.BuildConnectURLRequest) (string, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for BuildConnectURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(robinhood.BuildConnectURLRequest) (string, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(robinhood.BuildConnectURLRequest) string); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(robinhood.BuildConnectURLRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_BuildConnectURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuildConnectURL'
type MockClient_BuildConnectURL_Call struct {
	*mock.Call
}

// BuildConnectURL is a helper method to define mock.On call
//   - req robinhood.BuildConnectURLRequest
func (_e *MockClient_Expecter) BuildConnectURL(req interface{}) *MockClient_BuildConnectURL_Call {
	return &MockClient_BuildConnectURL_Call{Call: _e.mock.On("BuildConnectURL", req)}
}

func (_c *MockClient_BuildConnectURL_Call) Run(run func(req robinhood.BuildConnectURLRequest)) *MockClient_BuildConnectURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(robinhood.BuildConnectURLRequest))
	})
	return _c
}

func (_c *MockClient_BuildConnectURL_Call) Return(_a0 string, _a1 error) *MockClient_BuildConnectURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_BuildConnectURL_Call) RunAndReturn(run func(robinhood.BuildConnectURLRequest) (string, error)) *MockClient_BuildConnectURL_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function with no fields
func (_m *MockClient) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockClient_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockClient_Expecter) Close() *MockClient_Close_Call {
	return &MockClient_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockClient_Close_Call) Run(run func()) *MockClient_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Close_Call) Return(_a0 error) *MockClient_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_Close_Call) RunAndReturn(run func() error) *MockClient_Close_Call {
	_c.Call.Return(run)
	return _c
}

// CreateConnectID provides a mock function with given fields: ctx, req
func (_m *MockClient) CreateConnectID(ctx context.Context, req robinhood.CreateConnectIDRequest) (*robinhood.CreateConnectIDResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateConnectID")
	}

	var r0 *robinhood.CreateConnectIDResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, robinhood.CreateConnectIDRequest) (*robinhood.CreateConnectIDResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, robinhood.CreateConnectIDRequest) *robinhood.CreateConnectIDResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*robinhood.CreateConnectIDResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, robinhood.CreateConnectIDRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_CreateConnectID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateConnectID'
type MockClient_CreateConnectID_Call struct {
	*mock.Call
}

// CreateConnectID is a helper method to define mock.On call
//   - ctx context.Context
//   - req robinhood.CreateConnectIDRequest
func (_e *MockClient_Expecter) CreateConnectID(ctx interface{}, req interface{}) *MockClient_CreateConnectID_Call {
	return &MockClient_CreateConnectID_Call{Call: _e.mock.On("CreateConnectID", ctx, req)}
}

func (_c *MockClient_CreateConnectID_Call) Run(run func(ctx context.Context, req robinhood.CreateConnectIDRequest)) *MockClient_CreateConnectID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(robinhood.CreateConnectIDRequest))
	})
	return _c
}

func (_c *MockClient_CreateConnectID_Call) Return(_a0 *robinhood.CreateConnectIDResponse, _a1 error) *MockClient_CreateConnectID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_CreateConnectID_Call) RunAndReturn(run func(context.Context, robinhood.CreateConnectIDRequest) (*robinhood.CreateConnectIDResponse, error)) *MockClient_CreateConnectID_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrder provides a mock function with given fields: ctx, connectID
func (_m *MockClient) GetOrder(ctx context.Context, connectID string) (*robinhood.Order, error) {
	ret := _m.Called(ctx, connectID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 *robinhood.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*robinhood.Order, error)); ok {
		return rf(ctx, connectID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *robinhood.Order); ok {
		r0 = rf(ctx, connectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*robinhood.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, connectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type MockClient_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - connectID string
func (_e *MockClient_Expecter) GetOrder(ctx interface{}, connectID interface{}) *MockClient_GetOrder_Call {
	return &MockClient_GetOrder_Call{Call: _e.mock.On("GetOrder", ctx, connectID)}
}

func (_c *MockClient_GetOrder_Call) Run(run func(ctx context.Context, connectID string)) *MockClient_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClient_GetOrder_Call) Return(_a0 *robinhood.Order, _a1 error) *MockClient_GetOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetOrder_Call) RunAndReturn(run func(context.Context, string) (*robinhood.Order, error)) *MockClient_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
