// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	yahoo "github.com/superform-xyz/superform-go-utils/providers/yahoo"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockClient) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockClient_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockClient_Expecter) Close() *MockClient_Close_Call {
	return &MockClient_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockClient_Close_Call) Run(run func()) *MockClient_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Close_Call) Return(_a0 error) *MockClient_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_Close_Call) RunAndReturn(run func() error) *MockClient_Close_Call {
	_c.Call.Return(run)
	return _c
}

// GetChart provides a mock function with given fields: ctx, req
func (_m *MockClient) GetChart(ctx context.Context, req yahoo.ChartRequest) (*yahoo.ChartResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetChart")
	}

	var r0 *yahoo.ChartResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, yahoo.ChartRequest) (*yahoo.ChartResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, yahoo.ChartRequest) *yahoo.ChartResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*yahoo.ChartResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, yahoo.ChartRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetChart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChart'
type MockClient_GetChart_Call struct {
	*mock.Call
}

// GetChart is a helper method to define mock.On call
//   - ctx context.Context
//   - req yahoo.ChartRequest
func (_e *MockClient_Expecter) GetChart(ctx interface{}, req interface{}) *MockClient_GetChart_Call {
	return &MockClient_GetChart_Call{Call: _e.mock.On("GetChart", ctx, req)}
}

func (_c *MockClient_GetChart_Call) Run(run func(ctx context.Context, req yahoo.ChartRequest)) *MockClient_GetChart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(yahoo.ChartRequest))
	})
	return _c
}

func (_c *MockClient_GetChart_Call) Return(_a0 *yahoo.ChartResponse, _a1 error) *MockClient_GetChart_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetChart_Call) RunAndReturn(run func(context.Context, yahoo.ChartRequest) (*yahoo.ChartResponse, error)) *MockClient_GetChart_Call {
	_c.Call.Return(run)
	return _c
}

// GetPriceHistory provides a mock function with given fields: ctx, req
func (_m *MockClient) GetPriceHistory(ctx context.Context, req yahoo.PriceHistoryRequest) ([]yahoo.PriceBar, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetPriceHistory")
	}

	var r0 []yahoo.PriceBar
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, yahoo.PriceHistoryRequest) ([]yahoo.PriceBar, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, yahoo.PriceHistoryRequest) []yahoo.PriceBar); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]yahoo.PriceBar)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, yahoo.PriceHistoryRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetPriceHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPriceHistory'
type MockClient_GetPriceHistory_Call struct {
	*mock.Call
}

// GetPriceHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - req yahoo.PriceHistoryRequest
func (_e *MockClient_Expecter) GetPriceHistory(ctx interface{}, req interface{}) *MockClient_GetPriceHistory_Call {
	return &MockClient_GetPriceHistory_Call{Call: _e.mock.On("GetPriceHistory", ctx, req)}
}

func (_c *MockClient_GetPriceHistory_Call) Run(run func(ctx context.Context, req yahoo.PriceHistoryRequest)) *MockClient_GetPriceHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(yahoo.PriceHistoryRequest))
	})
	return _c
}

func (_c *MockClient_GetPriceHistory_Call) Return(_a0 []yahoo.PriceBar, _a1 error) *MockClient_GetPriceHistory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetPriceHistory_Call) RunAndReturn(run func(context.Context, yahoo.PriceHistoryRequest) ([]yahoo.PriceBar, error)) *MockClient_GetPriceHistory_Call {
	_c.Call.Return(run)
	return _c
}

// GetStockDetail provides a mock function with given fields: ctx, symbol
func (_m *MockClient) GetStockDetail(ctx context.Context, symbol string) (*yahoo.StockDetail, error) {
	ret := _m.Called(ctx, symbol)

	if len(ret) == 0 {
		panic("no return value specified for GetStockDetail")
	}

	var r0 *yahoo.StockDetail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*yahoo.StockDetail, error)); ok {
		return rf(ctx, symbol)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *yahoo.StockDetail); ok {
		r0 = rf(ctx, symbol)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*yahoo.StockDetail)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, symbol)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetStockDetail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStockDetail'
type MockClient_GetStockDetail_Call struct {
	*mock.Call
}

// GetStockDetail is a helper method to define mock.On call
//   - ctx context.Context
//   - symbol string
func (_e *MockClient_Expecter) GetStockDetail(ctx interface{}, symbol interface{}) *MockClient_GetStockDetail_Call {
	return &MockClient_GetStockDetail_Call{Call: _e.mock.On("GetStockDetail", ctx, symbol)}
}

func (_c *MockClient_GetStockDetail_Call) Run(run func(ctx context.Context, symbol string)) *MockClient_GetStockDetail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClient_GetStockDetail_Call) Return(_a0 *yahoo.StockDetail, _a1 error) *MockClient_GetStockDetail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetStockDetail_Call) RunAndReturn(run func(context.Context, string) (*yahoo.StockDetail, error)) *MockClient_GetStockDetail_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
