// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	coinbase "github.com/superform-xyz/superform-go-utils/providers/coinbase"

	mock "github.com/stretchr/testify/mock"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// BuildBuyURL provides a mock function with given fields: req
func (_m *MockClient) BuildBuyURL(req coinbase.BuildBuyURLRequest) (string, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for BuildBuyURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(coinbase.BuildBuyURLRequest) (string, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(coinbase.BuildBuyURLRequest) string); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(coinbase.BuildBuyURLRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_BuildBuyURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuildBuyURL'
type MockClient_BuildBuyURL_Call struct {
	*mock.Call
}

// BuildBuyURL is a helper method to define mock.On call
//   - req coinbase.BuildBuyURLRequest
func (_e *MockClient_Expecter) BuildBuyURL(req interface{}) *MockClient_BuildBuyURL_Call {
	return &MockClient_BuildBuyURL_Call{Call: _e.mock.On("BuildBuyURL", req)}
}

func (_c *MockClient_BuildBuyURL_Call) Run(run func(req coinbase.BuildBuyURLRequest)) *MockClient_BuildBuyURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(coinbase.BuildBuyURLRequest))
	})
	return _c
}

func (_c *MockClient_BuildBuyURL_Call) Return(_a0 string, _a1 error) *MockClient_BuildBuyURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_BuildBuyURL_Call) RunAndReturn(run func(coinbase.BuildBuyURLRequest) (string, error)) *MockClient_BuildBuyURL_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function with no fields
func (_m *MockClient) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockClient_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockClient_Expecter) Close() *MockClient_Close_Call {
	return &MockClient_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockClient_Close_Call) Run(run func()) *MockClient_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Close_Call) Return(_a0 error) *MockClient_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_Close_Call) RunAndReturn(run func() error) *MockClient_Close_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSessionToken provides a mock function with given fields: ctx, req
func (_m *MockClient) CreateSessionToken(ctx context.Context, req coinbase.CreateSessionTokenRequest) (*coinbase.CreateSessionTokenResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateSessionToken")
	}

	var r0 *coinbase.CreateSessionTokenResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, coinbase.CreateSessionTokenRequest) (*coinbase.CreateSessionTokenResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, coinbase.CreateSessionTokenRequest) *coinbase.CreateSessionTokenResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coinbase.CreateSessionTokenResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, coinbase.CreateSessionTokenRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_CreateSessionToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSessionToken'
type MockClient_CreateSessionToken_Call struct {
	*mock.Call
}

// CreateSessionToken is a helper method to define mock.On call
//   - ctx context.Context
//   - req coinbase.CreateSessionTokenRequest
func (_e *MockClient_Expecter) CreateSessionToken(ctx interface{}, req interface{}) *MockClient_CreateSessionToken_Call {
	return &MockClient_CreateSessionToken_Call{Call: _e.mock.On("CreateSessionToken", ctx, req)}
}

func (_c *MockClient_CreateSessionToken_Call) Run(run func(ctx context.Context, req coinbase.CreateSessionTokenRequest)) *MockClient_CreateSessionToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(coinbase.CreateSessionTokenRequest))
	})
	return _c
}

func (_c *MockClient_CreateSessionToken_Call) Return(_a0 *coinbase.CreateSessionTokenResponse, _a1 error) *MockClient_CreateSessionToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_CreateSessionToken_Call) RunAndReturn(run func(context.Context, coinbase.CreateSessionTokenRequest) (*coinbase.CreateSessionTokenResponse, error)) *MockClient_CreateSessionToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetBuyConfig provides a mock function with given fields: ctx
func (_m *MockClient) GetBuyConfig(ctx context.Context) (*coinbase.GetBuyConfigResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetBuyConfig")
	}

	var r0 *coinbase.GetBuyConfigResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*coinbase.GetBuyConfigResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *coinbase.GetBuyConfigResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coinbase.GetBuyConfigResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetBuyConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBuyConfig'
type MockClient_GetBuyConfig_Call struct {
	*mock.Call
}

// GetBuyConfig is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClient_Expecter) GetBuyConfig(ctx interface{}) *MockClient_GetBuyConfig_Call {
	return &MockClient_GetBuyConfig_Call{Call: _e.mock.On("GetBuyConfig", ctx)}
}

func (_c *MockClient_GetBuyConfig_Call) Run(run func(ctx context.Context)) *MockClient_GetBuyConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockClient_GetBuyConfig_Call) Return(_a0 *coinbase.GetBuyConfigResponse, _a1 error) *MockClient_GetBuyConfig_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetBuyConfig_Call) RunAndReturn(run func(context.Context) (*coinbase.GetBuyConfigResponse, error)) *MockClient_GetBuyConfig_Call {
	_c.Call.Return(run)
	return _c
}

// GetBuyOptions provides a mock function with given fields: ctx, req
func (_m *MockClient) GetBuyOptions(ctx context.Context, req coinbase.GetBuyOptionsRequest) (*coinbase.GetBuyOptionsResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetBuyOptions")
	}

	var r0 *coinbase.GetBuyOptionsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, coinbase.GetBuyOptionsRequest) (*coinbase.GetBuyOptionsResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, coinbase.GetBuyOptionsRequest) *coinbase.GetBuyOptionsResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coinbase.GetBuyOptionsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, coinbase.GetBuyOptionsRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetBuyOptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBuyOptions'
type MockClient_GetBuyOptions_Call struct {
	*mock.Call
}

// GetBuyOptions is a helper method to define mock.On call
//   - ctx context.Context
//   - req coinbase.GetBuyOptionsRequest
func (_e *MockClient_Expecter) GetBuyOptions(ctx interface{}, req interface{}) *MockClient_GetBuyOptions_Call {
	return &MockClient_GetBuyOptions_Call{Call: _e.mock.On("GetBuyOptions", ctx, req)}
}

func (_c *MockClient_GetBuyOptions_Call) Run(run func(ctx context.Context, req coinbase.GetBuyOptionsRequest)) *MockClient_GetBuyOptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(coinbase.GetBuyOptionsRequest))
	})
	return _c
}

func (_c *MockClient_GetBuyOptions_Call) Return(_a0 *coinbase.GetBuyOptionsResponse, _a1 error) *MockClient_GetBuyOptions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetBuyOptions_Call) RunAndReturn(run func(context.Context, coinbase.GetBuyOptionsRequest) (*coinbase.GetBuyOptionsResponse, error)) *MockClient_GetBuyOptions_Call {
	_c.Call.Return(run)
	return _c
}

// GetBuyTransactions provides a mock function with given fields: ctx, req
func (_m *MockClient) GetBuyTransactions(ctx context.Context, req coinbase.GetBuyTransactionsRequest) (*coinbase.GetBuyTransactionsResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetBuyTransactions")
	}

	var r0 *coinbase.GetBuyTransactionsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, coinbase.GetBuyTransactionsRequest) (*coinbase.GetBuyTransactionsResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, coinbase.GetBuyTransactionsRequest) *coinbase.GetBuyTransactionsResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*coinbase.GetBuyTransactionsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, coinbase.GetBuyTransactionsRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetBuyTransactions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBuyTransactions'
type MockClient_GetBuyTransactions_Call struct {
	*mock.Call
}

// GetBuyTransactions is a helper method to define mock.On call
//   - ctx context.Context
//   - req coinbase.GetBuyTransactionsRequest
func (_e *MockClient_Expecter) GetBuyTransactions(ctx interface{}, req interface{}) *MockClient_GetBuyTransactions_Call {
	return &MockClient_GetBuyTransactions_Call{Call: _e.mock.On("GetBuyTransactions", ctx, req)}
}

func (_c *MockClient_GetBuyTransactions_Call) Run(run func(ctx context.Context, req coinbase.GetBuyTransactionsRequest)) *MockClient_GetBuyTransactions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(coinbase.GetBuyTransactionsRequest))
	})
	return _c
}

func (_c *MockClient_GetBuyTransactions_Call) Return(_a0 *coinbase.GetBuyTransactionsResponse, _a1 error) *MockClient_GetBuyTransactions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetBuyTransactions_Call) RunAndReturn(run func(context.Context, coinbase.GetBuyTransactionsRequest) (*coinbase.GetBuyTransactionsResponse, error)) *MockClient_GetBuyTransactions_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
