// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	common "github.com/ethereum/go-ethereum/common"

	mock "github.com/stretchr/testify/mock"

	oneinch "github.com/superform-xyz/superform-go-utils/providers/oneinch"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockClient) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockClient_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockClient_Expecter) Close() *MockClient_Close_Call {
	return &MockClient_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockClient_Close_Call) Run(run func()) *MockClient_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Close_Call) Return(_a0 error) *MockClient_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_Close_Call) RunAndReturn(run func() error) *MockClient_Close_Call {
	_c.Call.Return(run)
	return _c
}

// GetQuote provides a mock function with given fields: ctx, req
func (_m *MockClient) GetQuote(ctx context.Context, req oneinch.QuoteRequest) (*oneinch.Quote, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetQuote")
	}

	var r0 *oneinch.Quote
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, oneinch.QuoteRequest) (*oneinch.Quote, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, oneinch.QuoteRequest) *oneinch.Quote); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oneinch.Quote)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, oneinch.QuoteRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetQuote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQuote'
type MockClient_GetQuote_Call struct {
	*mock.Call
}

// GetQuote is a helper method to define mock.On call
//   - ctx context.Context
//   - req oneinch.QuoteRequest
func (_e *MockClient_Expecter) GetQuote(ctx interface{}, req interface{}) *MockClient_GetQuote_Call {
	return &MockClient_GetQuote_Call{Call: _e.mock.On("GetQuote", ctx, req)}
}

func (_c *MockClient_GetQuote_Call) Run(run func(ctx context.Context, req oneinch.QuoteRequest)) *MockClient_GetQuote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(oneinch.QuoteRequest))
	})
	return _c
}

func (_c *MockClient_GetQuote_Call) Return(_a0 *oneinch.Quote, _a1 error) *MockClient_GetQuote_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetQuote_Call) RunAndReturn(run func(context.Context, oneinch.QuoteRequest) (*oneinch.Quote, error)) *MockClient_GetQuote_Call {
	_c.Call.Return(run)
	return _c
}

// GetRouter provides a mock function with given fields: chainID
func (_m *MockClient) GetRouter(chainID uint64) common.Address {
	ret := _m.Called(chainID)

	if len(ret) == 0 {
		panic("no return value specified for GetRouter")
	}

	var r0 common.Address
	if rf, ok := ret.Get(0).(func(uint64) common.Address); ok {
		r0 = rf(chainID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(common.Address)
		}
	}

	return r0
}

// MockClient_GetRouter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRouter'
type MockClient_GetRouter_Call struct {
	*mock.Call
}

// GetRouter is a helper method to define mock.On call
//   - chainID uint64
func (_e *MockClient_Expecter) GetRouter(chainID interface{}) *MockClient_GetRouter_Call {
	return &MockClient_GetRouter_Call{Call: _e.mock.On("GetRouter", chainID)}
}

func (_c *MockClient_GetRouter_Call) Run(run func(chainID uint64)) *MockClient_GetRouter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint64))
	})
	return _c
}

func (_c *MockClient_GetRouter_Call) Return(_a0 common.Address) *MockClient_GetRouter_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_GetRouter_Call) RunAndReturn(run func(uint64) common.Address) *MockClient_GetRouter_Call {
	_c.Call.Return(run)
	return _c
}

// GetSwap provides a mock function with given fields: ctx, req
func (_m *MockClient) GetSwap(ctx context.Context, req oneinch.SwapRequest) (*oneinch.Swap, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetSwap")
	}

	var r0 *oneinch.Swap
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, oneinch.SwapRequest) (*oneinch.Swap, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, oneinch.SwapRequest) *oneinch.Swap); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oneinch.Swap)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, oneinch.SwapRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetSwap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSwap'
type MockClient_GetSwap_Call struct {
	*mock.Call
}

// GetSwap is a helper method to define mock.On call
//   - ctx context.Context
//   - req oneinch.SwapRequest
func (_e *MockClient_Expecter) GetSwap(ctx interface{}, req interface{}) *MockClient_GetSwap_Call {
	return &MockClient_GetSwap_Call{Call: _e.mock.On("GetSwap", ctx, req)}
}

func (_c *MockClient_GetSwap_Call) Run(run func(ctx context.Context, req oneinch.SwapRequest)) *MockClient_GetSwap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(oneinch.SwapRequest))
	})
	return _c
}

func (_c *MockClient_GetSwap_Call) Return(_a0 *oneinch.Swap, _a1 error) *MockClient_GetSwap_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetSwap_Call) RunAndReturn(run func(context.Context, oneinch.SwapRequest) (*oneinch.Swap, error)) *MockClient_GetSwap_Call {
	_c.Call.Return(run)
	return _c
}

// SupportedChains provides a mock function with no fields
func (_m *MockClient) SupportedChains() []uint64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SupportedChains")
	}

	var r0 []uint64
	if rf, ok := ret.Get(0).(func() []uint64); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uint64)
		}
	}

	return r0
}

// MockClient_SupportedChains_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SupportedChains'
type MockClient_SupportedChains_Call struct {
	*mock.Call
}

// SupportedChains is a helper method to define mock.On call
func (_e *MockClient_Expecter) SupportedChains() *MockClient_SupportedChains_Call {
	return &MockClient_SupportedChains_Call{Call: _e.mock.On("SupportedChains")}
}

func (_c *MockClient_SupportedChains_Call) Run(run func()) *MockClient_SupportedChains_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_SupportedChains_Call) Return(_a0 []uint64) *MockClient_SupportedChains_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_SupportedChains_Call) RunAndReturn(run func() []uint64) *MockClient_SupportedChains_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
