// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	common "github.com/ethereum/go-ethereum/common"

	debank "github.com/superform-xyz/superform-go-utils/providers/debank"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockDebank is an autogenerated mock type for the Debank type
type MockDebank struct {
	mock.Mock
}

type MockDebank_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDebank) EXPECT() *MockDebank_Expecter {
	return &MockDebank_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockDebank) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDebank_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockDebank_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockDebank_Expecter) Close() *MockDebank_Close_Call {
	return &MockDebank_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockDebank_Close_Call) Run(run func()) *MockDebank_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDebank_Close_Call) Return(_a0 error) *MockDebank_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDebank_Close_Call) RunAndReturn(run func() error) *MockDebank_Close_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccountCredits provides a mock function with given fields: ctx
func (_m *MockDebank) GetAccountCredits(ctx context.Context) (debank.AccountCredits, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountCredits")
	}

	var r0 debank.AccountCredits
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (debank.AccountCredits, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) debank.AccountCredits); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(debank.AccountCredits)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDebank_GetAccountCredits_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccountCredits'
type MockDebank_GetAccountCredits_Call struct {
	*mock.Call
}

// GetAccountCredits is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDebank_Expecter) GetAccountCredits(ctx interface{}) *MockDebank_GetAccountCredits_Call {
	return &MockDebank_GetAccountCredits_Call{Call: _e.mock.On("GetAccountCredits", ctx)}
}

func (_c *MockDebank_GetAccountCredits_Call) Run(run func(ctx context.Context)) *MockDebank_GetAccountCredits_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDebank_GetAccountCredits_Call) Return(_a0 debank.AccountCredits, _a1 error) *MockDebank_GetAccountCredits_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDebank_GetAccountCredits_Call) RunAndReturn(run func(context.Context) (debank.AccountCredits, error)) *MockDebank_GetAccountCredits_Call {
	_c.Call.Return(run)
	return _c
}

// GetHistoryTokenPrice provides a mock function with given fields: ctx, chainID, tokenAddress, timestamp
func (_m *MockDebank) GetHistoryTokenPrice(ctx context.Context, chainID uint64, tokenAddress common.Address, timestamp time.Time) (*float64, error) {
	ret := _m.Called(ctx, chainID, tokenAddress, timestamp)

	if len(ret) == 0 {
		panic("no return value specified for GetHistoryTokenPrice")
	}

	var r0 *float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, common.Address, time.Time) (*float64, error)); ok {
		return rf(ctx, chainID, tokenAddress, timestamp)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64, common.Address, time.Time) *float64); ok {
		r0 = rf(ctx, chainID, tokenAddress, timestamp)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*float64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64, common.Address, time.Time) error); ok {
		r1 = rf(ctx, chainID, tokenAddress, timestamp)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDebank_GetHistoryTokenPrice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHistoryTokenPrice'
type MockDebank_GetHistoryTokenPrice_Call struct {
	*mock.Call
}

// GetHistoryTokenPrice is a helper method to define mock.On call
//   - ctx context.Context
//   - chainID uint64
//   - tokenAddress common.Address
//   - timestamp time.Time
func (_e *MockDebank_Expecter) GetHistoryTokenPrice(ctx interface{}, chainID interface{}, tokenAddress interface{}, timestamp interface{}) *MockDebank_GetHistoryTokenPrice_Call {
	return &MockDebank_GetHistoryTokenPrice_Call{Call: _e.mock.On("GetHistoryTokenPrice", ctx, chainID, tokenAddress, timestamp)}
}

func (_c *MockDebank_GetHistoryTokenPrice_Call) Run(run func(ctx context.Context, chainID uint64, tokenAddress common.Address, timestamp time.Time)) *MockDebank_GetHistoryTokenPrice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].(common.Address), args[3].(time.Time))
	})
	return _c
}

func (_c *MockDebank_GetHistoryTokenPrice_Call) Return(_a0 *float64, _a1 error) *MockDebank_GetHistoryTokenPrice_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDebank_GetHistoryTokenPrice_Call) RunAndReturn(run func(context.Context, uint64, common.Address, time.Time) (*float64, error)) *MockDebank_GetHistoryTokenPrice_Call {
	_c.Call.Return(run)
	return _c
}

// GetProtocolPortfolios provides a mock function with given fields: ctx, userAddress
func (_m *MockDebank) GetProtocolPortfolios(ctx context.Context, userAddress string) ([]debank.ProtocolPortfolio, error) {
	ret := _m.Called(ctx, userAddress)

	if len(ret) == 0 {
		panic("no return value specified for GetProtocolPortfolios")
	}

	var r0 []debank.ProtocolPortfolio
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]debank.ProtocolPortfolio, error)); ok {
		return rf(ctx, userAddress)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []debank.ProtocolPortfolio); ok {
		r0 = rf(ctx, userAddress)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]debank.ProtocolPortfolio)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userAddress)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDebank_GetProtocolPortfolios_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProtocolPortfolios'
type MockDebank_GetProtocolPortfolios_Call struct {
	*mock.Call
}

// GetProtocolPortfolios is a helper method to define mock.On call
//   - ctx context.Context
//   - userAddress string
func (_e *MockDebank_Expecter) GetProtocolPortfolios(ctx interface{}, userAddress interface{}) *MockDebank_GetProtocolPortfolios_Call {
	return &MockDebank_GetProtocolPortfolios_Call{Call: _e.mock.On("GetProtocolPortfolios", ctx, userAddress)}
}

func (_c *MockDebank_GetProtocolPortfolios_Call) Run(run func(ctx context.Context, userAddress string)) *MockDebank_GetProtocolPortfolios_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDebank_GetProtocolPortfolios_Call) Return(_a0 []debank.ProtocolPortfolio, _a1 error) *MockDebank_GetProtocolPortfolios_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDebank_GetProtocolPortfolios_Call) RunAndReturn(run func(context.Context, string) ([]debank.ProtocolPortfolio, error)) *MockDebank_GetProtocolPortfolios_Call {
	_c.Call.Return(run)
	return _c
}

// GetToken provides a mock function with given fields: ctx, chainID, tokenAddress
func (_m *MockDebank) GetToken(ctx context.Context, chainID uint64, tokenAddress common.Address) (*debank.Token, error) {
	ret := _m.Called(ctx, chainID, tokenAddress)

	if len(ret) == 0 {
		panic("no return value specified for GetToken")
	}

	var r0 *debank.Token
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, common.Address) (*debank.Token, error)); ok {
		return rf(ctx, chainID, tokenAddress)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64, common.Address) *debank.Token); ok {
		r0 = rf(ctx, chainID, tokenAddress)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*debank.Token)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64, common.Address) error); ok {
		r1 = rf(ctx, chainID, tokenAddress)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDebank_GetToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetToken'
type MockDebank_GetToken_Call struct {
	*mock.Call
}

// GetToken is a helper method to define mock.On call
//   - ctx context.Context
//   - chainID uint64
//   - tokenAddress common.Address
func (_e *MockDebank_Expecter) GetToken(ctx interface{}, chainID interface{}, tokenAddress interface{}) *MockDebank_GetToken_Call {
	return &MockDebank_GetToken_Call{Call: _e.mock.On("GetToken", ctx, chainID, tokenAddress)}
}

func (_c *MockDebank_GetToken_Call) Run(run func(ctx context.Context, chainID uint64, tokenAddress common.Address)) *MockDebank_GetToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].(common.Address))
	})
	return _c
}

func (_c *MockDebank_GetToken_Call) Return(_a0 *debank.Token, _a1 error) *MockDebank_GetToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDebank_GetToken_Call) RunAndReturn(run func(context.Context, uint64, common.Address) (*debank.Token, error)) *MockDebank_GetToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetTokenBalances provides a mock function with given fields: ctx, address, filterTokens
func (_m *MockDebank) GetTokenBalances(ctx context.Context, address string, filterTokens bool) ([]debank.Token, error) {
	ret := _m.Called(ctx, address, filterTokens)

	if len(ret) == 0 {
		panic("no return value specified for GetTokenBalances")
	}

	var r0 []debank.Token
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) ([]debank.Token, error)); ok {
		return rf(ctx, address, filterTokens)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) []debank.Token); ok {
		r0 = rf(ctx, address, filterTokens)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]debank.Token)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, bool) error); ok {
		r1 = rf(ctx, address, filterTokens)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDebank_GetTokenBalances_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTokenBalances'
type MockDebank_GetTokenBalances_Call struct {
	*mock.Call
}

// GetTokenBalances is a helper method to define mock.On call
//   - ctx context.Context
//   - address string
//   - filterTokens bool
func (_e *MockDebank_Expecter) GetTokenBalances(ctx interface{}, address interface{}, filterTokens interface{}) *MockDebank_GetTokenBalances_Call {
	return &MockDebank_GetTokenBalances_Call{Call: _e.mock.On("GetTokenBalances", ctx, address, filterTokens)}
}

func (_c *MockDebank_GetTokenBalances_Call) Run(run func(ctx context.Context, address string, filterTokens bool)) *MockDebank_GetTokenBalances_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(bool))
	})
	return _c
}

func (_c *MockDebank_GetTokenBalances_Call) Return(_a0 []debank.Token, _a1 error) *MockDebank_GetTokenBalances_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDebank_GetTokenBalances_Call) RunAndReturn(run func(context.Context, string, bool) ([]debank.Token, error)) *MockDebank_GetTokenBalances_Call {
	_c.Call.Return(run)
	return _c
}

// GetTokens provides a mock function with given fields: ctx, chainID, tokenAddresses
func (_m *MockDebank) GetTokens(ctx context.Context, chainID uint64, tokenAddresses []common.Address) ([]debank.Token, error) {
	ret := _m.Called(ctx, chainID, tokenAddresses)

	if len(ret) == 0 {
		panic("no return value specified for GetTokens")
	}

	var r0 []debank.Token
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, []common.Address) ([]debank.Token, error)); ok {
		return rf(ctx, chainID, tokenAddresses)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64, []common.Address) []debank.Token); ok {
		r0 = rf(ctx, chainID, tokenAddresses)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]debank.Token)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64, []common.Address) error); ok {
		r1 = rf(ctx, chainID, tokenAddresses)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDebank_GetTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTokens'
type MockDebank_GetTokens_Call struct {
	*mock.Call
}

// GetTokens is a helper method to define mock.On call
//   - ctx context.Context
//   - chainID uint64
//   - tokenAddresses []common.Address
func (_e *MockDebank_Expecter) GetTokens(ctx interface{}, chainID interface{}, tokenAddresses interface{}) *MockDebank_GetTokens_Call {
	return &MockDebank_GetTokens_Call{Call: _e.mock.On("GetTokens", ctx, chainID, tokenAddresses)}
}

func (_c *MockDebank_GetTokens_Call) Run(run func(ctx context.Context, chainID uint64, tokenAddresses []common.Address)) *MockDebank_GetTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].([]common.Address))
	})
	return _c
}

func (_c *MockDebank_GetTokens_Call) Return(_a0 []debank.Token, _a1 error) *MockDebank_GetTokens_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDebank_GetTokens_Call) RunAndReturn(run func(context.Context, uint64, []common.Address) ([]debank.Token, error)) *MockDebank_GetTokens_Call {
	_c.Call.Return(run)
	return _c
}

// HealthCheck provides a mock function with given fields: ctx
func (_m *MockDebank) HealthCheck(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for HealthCheck")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDebank_HealthCheck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HealthCheck'
type MockDebank_HealthCheck_Call struct {
	*mock.Call
}

// HealthCheck is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDebank_Expecter) HealthCheck(ctx interface{}) *MockDebank_HealthCheck_Call {
	return &MockDebank_HealthCheck_Call{Call: _e.mock.On("HealthCheck", ctx)}
}

func (_c *MockDebank_HealthCheck_Call) Run(run func(ctx context.Context)) *MockDebank_HealthCheck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDebank_HealthCheck_Call) Return(_a0 error) *MockDebank_HealthCheck_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDebank_HealthCheck_Call) RunAndReturn(run func(context.Context) error) *MockDebank_HealthCheck_Call {
	_c.Call.Return(run)
	return _c
}

// SupportedChains provides a mock function with no fields
func (_m *MockDebank) SupportedChains() []uint64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SupportedChains")
	}

	var r0 []uint64
	if rf, ok := ret.Get(0).(func() []uint64); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uint64)
		}
	}

	return r0
}

// MockDebank_SupportedChains_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SupportedChains'
type MockDebank_SupportedChains_Call struct {
	*mock.Call
}

// SupportedChains is a helper method to define mock.On call
func (_e *MockDebank_Expecter) SupportedChains() *MockDebank_SupportedChains_Call {
	return &MockDebank_SupportedChains_Call{Call: _e.mock.On("SupportedChains")}
}

func (_c *MockDebank_SupportedChains_Call) Run(run func()) *MockDebank_SupportedChains_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDebank_SupportedChains_Call) Return(_a0 []uint64) *MockDebank_SupportedChains_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDebank_SupportedChains_Call) RunAndReturn(run func() []uint64) *MockDebank_SupportedChains_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDebank creates a new instance of MockDebank. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDebank(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDebank {
	mock := &MockDebank{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
