// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	common "github.com/ethereum/go-ethereum/common"
	mock "github.com/stretchr/testify/mock"
	defillama "github.com/superform-xyz/superform-go-utils/providers/defillama"

	time "time"
)

// MockDefiLlama is an autogenerated mock type for the DefiLlama type
type MockDefiLlama struct {
	mock.Mock
}

type MockDefiLlama_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDefiLlama) EXPECT() *MockDefiLlama_Expecter {
	return &MockDefiLlama_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockDefiLlama) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDefiLlama_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockDefiLlama_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockDefiLlama_Expecter) Close() *MockDefiLlama_Close_Call {
	return &MockDefiLlama_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockDefiLlama_Close_Call) Run(run func()) *MockDefiLlama_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDefiLlama_Close_Call) Return(_a0 error) *MockDefiLlama_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDefiLlama_Close_Call) RunAndReturn(run func() error) *MockDefiLlama_Close_Call {
	_c.Call.Return(run)
	return _c
}

// GetCoin provides a mock function with given fields: chainId, tokenAddress
func (_m *MockDefiLlama) GetCoin(chainId uint64, tokenAddress common.Address) (*defillama.Coin, error) {
	ret := _m.Called(chainId, tokenAddress)

	if len(ret) == 0 {
		panic("no return value specified for GetCoin")
	}

	var r0 *defillama.Coin
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64, common.Address) (*defillama.Coin, error)); ok {
		return rf(chainId, tokenAddress)
	}
	if rf, ok := ret.Get(0).(func(uint64, common.Address) *defillama.Coin); ok {
		r0 = rf(chainId, tokenAddress)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*defillama.Coin)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64, common.Address) error); ok {
		r1 = rf(chainId, tokenAddress)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDefiLlama_GetCoin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCoin'
type MockDefiLlama_GetCoin_Call struct {
	*mock.Call
}

// GetCoin is a helper method to define mock.On call
//   - chainId uint64
//   - tokenAddress common.Address
func (_e *MockDefiLlama_Expecter) GetCoin(chainId interface{}, tokenAddress interface{}) *MockDefiLlama_GetCoin_Call {
	return &MockDefiLlama_GetCoin_Call{Call: _e.mock.On("GetCoin", chainId, tokenAddress)}
}

func (_c *MockDefiLlama_GetCoin_Call) Run(run func(chainId uint64, tokenAddress common.Address)) *MockDefiLlama_GetCoin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint64), args[1].(common.Address))
	})
	return _c
}

func (_c *MockDefiLlama_GetCoin_Call) Return(_a0 *defillama.Coin, _a1 error) *MockDefiLlama_GetCoin_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDefiLlama_GetCoin_Call) RunAndReturn(run func(uint64, common.Address) (*defillama.Coin, error)) *MockDefiLlama_GetCoin_Call {
	_c.Call.Return(run)
	return _c
}

// GetHistoricalCoin provides a mock function with given fields: chainId, tokenAddress, timestamp
func (_m *MockDefiLlama) GetHistoricalCoin(chainId uint64, tokenAddress common.Address, timestamp time.Time) (*defillama.Coin, error) {
	ret := _m.Called(chainId, tokenAddress, timestamp)

	if len(ret) == 0 {
		panic("no return value specified for GetHistoricalCoin")
	}

	var r0 *defillama.Coin
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64, common.Address, time.Time) (*defillama.Coin, error)); ok {
		return rf(chainId, tokenAddress, timestamp)
	}
	if rf, ok := ret.Get(0).(func(uint64, common.Address, time.Time) *defillama.Coin); ok {
		r0 = rf(chainId, tokenAddress, timestamp)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*defillama.Coin)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64, common.Address, time.Time) error); ok {
		r1 = rf(chainId, tokenAddress, timestamp)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDefiLlama_GetHistoricalCoin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHistoricalCoin'
type MockDefiLlama_GetHistoricalCoin_Call struct {
	*mock.Call
}

// GetHistoricalCoin is a helper method to define mock.On call
//   - chainId uint64
//   - tokenAddress common.Address
//   - timestamp time.Time
func (_e *MockDefiLlama_Expecter) GetHistoricalCoin(chainId interface{}, tokenAddress interface{}, timestamp interface{}) *MockDefiLlama_GetHistoricalCoin_Call {
	return &MockDefiLlama_GetHistoricalCoin_Call{Call: _e.mock.On("GetHistoricalCoin", chainId, tokenAddress, timestamp)}
}

func (_c *MockDefiLlama_GetHistoricalCoin_Call) Run(run func(chainId uint64, tokenAddress common.Address, timestamp time.Time)) *MockDefiLlama_GetHistoricalCoin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint64), args[1].(common.Address), args[2].(time.Time))
	})
	return _c
}

func (_c *MockDefiLlama_GetHistoricalCoin_Call) Return(_a0 *defillama.Coin, _a1 error) *MockDefiLlama_GetHistoricalCoin_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDefiLlama_GetHistoricalCoin_Call) RunAndReturn(run func(uint64, common.Address, time.Time) (*defillama.Coin, error)) *MockDefiLlama_GetHistoricalCoin_Call {
	_c.Call.Return(run)
	return _c
}

// GetMultipleCoins provides a mock function with given fields: tokens
func (_m *MockDefiLlama) GetMultipleCoins(tokens []defillama.QueryTokenPrice) ([]*defillama.Coin, error) {
	ret := _m.Called(tokens)

	if len(ret) == 0 {
		panic("no return value specified for GetMultipleCoins")
	}

	var r0 []*defillama.Coin
	var r1 error
	if rf, ok := ret.Get(0).(func([]defillama.QueryTokenPrice) ([]*defillama.Coin, error)); ok {
		return rf(tokens)
	}
	if rf, ok := ret.Get(0).(func([]defillama.QueryTokenPrice) []*defillama.Coin); ok {
		r0 = rf(tokens)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*defillama.Coin)
		}
	}

	if rf, ok := ret.Get(1).(func([]defillama.QueryTokenPrice) error); ok {
		r1 = rf(tokens)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDefiLlama_GetMultipleCoins_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMultipleCoins'
type MockDefiLlama_GetMultipleCoins_Call struct {
	*mock.Call
}

// GetMultipleCoins is a helper method to define mock.On call
//   - tokens []defillama.QueryTokenPrice
func (_e *MockDefiLlama_Expecter) GetMultipleCoins(tokens interface{}) *MockDefiLlama_GetMultipleCoins_Call {
	return &MockDefiLlama_GetMultipleCoins_Call{Call: _e.mock.On("GetMultipleCoins", tokens)}
}

func (_c *MockDefiLlama_GetMultipleCoins_Call) Run(run func(tokens []defillama.QueryTokenPrice)) *MockDefiLlama_GetMultipleCoins_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]defillama.QueryTokenPrice))
	})
	return _c
}

func (_c *MockDefiLlama_GetMultipleCoins_Call) Return(_a0 []*defillama.Coin, _a1 error) *MockDefiLlama_GetMultipleCoins_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDefiLlama_GetMultipleCoins_Call) RunAndReturn(run func([]defillama.QueryTokenPrice) ([]*defillama.Coin, error)) *MockDefiLlama_GetMultipleCoins_Call {
	_c.Call.Return(run)
	return _c
}

// HealthCheck provides a mock function with no fields
func (_m *MockDefiLlama) HealthCheck() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for HealthCheck")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDefiLlama_HealthCheck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HealthCheck'
type MockDefiLlama_HealthCheck_Call struct {
	*mock.Call
}

// HealthCheck is a helper method to define mock.On call
func (_e *MockDefiLlama_Expecter) HealthCheck() *MockDefiLlama_HealthCheck_Call {
	return &MockDefiLlama_HealthCheck_Call{Call: _e.mock.On("HealthCheck")}
}

func (_c *MockDefiLlama_HealthCheck_Call) Run(run func()) *MockDefiLlama_HealthCheck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDefiLlama_HealthCheck_Call) Return(_a0 error) *MockDefiLlama_HealthCheck_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDefiLlama_HealthCheck_Call) RunAndReturn(run func() error) *MockDefiLlama_HealthCheck_Call {
	_c.Call.Return(run)
	return _c
}

// SupportedChains provides a mock function with no fields
func (_m *MockDefiLlama) SupportedChains() []uint64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SupportedChains")
	}

	var r0 []uint64
	if rf, ok := ret.Get(0).(func() []uint64); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uint64)
		}
	}

	return r0
}

// MockDefiLlama_SupportedChains_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SupportedChains'
type MockDefiLlama_SupportedChains_Call struct {
	*mock.Call
}

// SupportedChains is a helper method to define mock.On call
func (_e *MockDefiLlama_Expecter) SupportedChains() *MockDefiLlama_SupportedChains_Call {
	return &MockDefiLlama_SupportedChains_Call{Call: _e.mock.On("SupportedChains")}
}

func (_c *MockDefiLlama_SupportedChains_Call) Run(run func()) *MockDefiLlama_SupportedChains_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDefiLlama_SupportedChains_Call) Return(_a0 []uint64) *MockDefiLlama_SupportedChains_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDefiLlama_SupportedChains_Call) RunAndReturn(run func() []uint64) *MockDefiLlama_SupportedChains_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDefiLlama creates a new instance of MockDefiLlama. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDefiLlama(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDefiLlama {
	mock := &MockDefiLlama{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
