// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	snapshotd "github.com/superform-xyz/superform-go-utils/providers/snapshotd"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockClient) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockClient_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockClient_Expecter) Close() *MockClient_Close_Call {
	return &MockClient_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockClient_Close_Call) Run(run func()) *MockClient_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Close_Call) Return(_a0 error) *MockClient_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_Close_Call) RunAndReturn(run func() error) *MockClient_Close_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllocation provides a mock function with given fields: ctx, query
func (_m *MockClient) GetAllocation(ctx context.Context, query snapshotd.Query) (*snapshotd.Allocation, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetAllocation")
	}

	var r0 *snapshotd.Allocation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, snapshotd.Query) (*snapshotd.Allocation, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, snapshotd.Query) *snapshotd.Allocation); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*snapshotd.Allocation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, snapshotd.Query) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetAllocation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllocation'
type MockClient_GetAllocation_Call struct {
	*mock.Call
}

// GetAllocation is a helper method to define mock.On call
//   - ctx context.Context
//   - query snapshotd.Query
func (_e *MockClient_Expecter) GetAllocation(ctx interface{}, query interface{}) *MockClient_GetAllocation_Call {
	return &MockClient_GetAllocation_Call{Call: _e.mock.On("GetAllocation", ctx, query)}
}

func (_c *MockClient_GetAllocation_Call) Run(run func(ctx context.Context, query snapshotd.Query)) *MockClient_GetAllocation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(snapshotd.Query))
	})
	return _c
}

func (_c *MockClient_GetAllocation_Call) Return(_a0 *snapshotd.Allocation, _a1 error) *MockClient_GetAllocation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetAllocation_Call) RunAndReturn(run func(context.Context, snapshotd.Query) (*snapshotd.Allocation, error)) *MockClient_GetAllocation_Call {
	_c.Call.Return(run)
	return _c
}

// GetPPS provides a mock function with given fields: ctx, query
func (_m *MockClient) GetPPS(ctx context.Context, query snapshotd.Query) (*snapshotd.PPSResult, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetPPS")
	}

	var r0 *snapshotd.PPSResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, snapshotd.Query) (*snapshotd.PPSResult, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, snapshotd.Query) *snapshotd.PPSResult); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*snapshotd.PPSResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, snapshotd.Query) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetPPS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPPS'
type MockClient_GetPPS_Call struct {
	*mock.Call
}

// GetPPS is a helper method to define mock.On call
//   - ctx context.Context
//   - query snapshotd.Query
func (_e *MockClient_Expecter) GetPPS(ctx interface{}, query interface{}) *MockClient_GetPPS_Call {
	return &MockClient_GetPPS_Call{Call: _e.mock.On("GetPPS", ctx, query)}
}

func (_c *MockClient_GetPPS_Call) Run(run func(ctx context.Context, query snapshotd.Query)) *MockClient_GetPPS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(snapshotd.Query))
	})
	return _c
}

func (_c *MockClient_GetPPS_Call) Return(_a0 *snapshotd.PPSResult, _a1 error) *MockClient_GetPPS_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetPPS_Call) RunAndReturn(run func(context.Context, snapshotd.Query) (*snapshotd.PPSResult, error)) *MockClient_GetPPS_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
