// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	sec "github.com/superform-xyz/superform-go-utils/providers/sec"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockClient) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockClient_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockClient_Expecter) Close() *MockClient_Close_Call {
	return &MockClient_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockClient_Close_Call) Run(run func()) *MockClient_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Close_Call) Return(_a0 error) *MockClient_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_Close_Call) RunAndReturn(run func() error) *MockClient_Close_Call {
	_c.Call.Return(run)
	return _c
}

// GetCompanyFacts provides a mock function with given fields: ctx, cik
func (_m *MockClient) GetCompanyFacts(ctx context.Context, cik uint64) (*sec.CompanyFacts, error) {
	ret := _m.Called(ctx, cik)

	if len(ret) == 0 {
		panic("no return value specified for GetCompanyFacts")
	}

	var r0 *sec.CompanyFacts
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (*sec.CompanyFacts, error)); ok {
		return rf(ctx, cik)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) *sec.CompanyFacts); ok {
		r0 = rf(ctx, cik)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sec.CompanyFacts)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, cik)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetCompanyFacts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCompanyFacts'
type MockClient_GetCompanyFacts_Call struct {
	*mock.Call
}

// GetCompanyFacts is a helper method to define mock.On call
//   - ctx context.Context
//   - cik uint64
func (_e *MockClient_Expecter) GetCompanyFacts(ctx interface{}, cik interface{}) *MockClient_GetCompanyFacts_Call {
	return &MockClient_GetCompanyFacts_Call{Call: _e.mock.On("GetCompanyFacts", ctx, cik)}
}

func (_c *MockClient_GetCompanyFacts_Call) Run(run func(ctx context.Context, cik uint64)) *MockClient_GetCompanyFacts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockClient_GetCompanyFacts_Call) Return(_a0 *sec.CompanyFacts, _a1 error) *MockClient_GetCompanyFacts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetCompanyFacts_Call) RunAndReturn(run func(context.Context, uint64) (*sec.CompanyFacts, error)) *MockClient_GetCompanyFacts_Call {
	_c.Call.Return(run)
	return _c
}

// GetCompanyTickers provides a mock function with given fields: ctx
func (_m *MockClient) GetCompanyTickers(ctx context.Context) ([]sec.CompanyTicker, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetCompanyTickers")
	}

	var r0 []sec.CompanyTicker
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]sec.CompanyTicker, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []sec.CompanyTicker); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sec.CompanyTicker)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetCompanyTickers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCompanyTickers'
type MockClient_GetCompanyTickers_Call struct {
	*mock.Call
}

// GetCompanyTickers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClient_Expecter) GetCompanyTickers(ctx interface{}) *MockClient_GetCompanyTickers_Call {
	return &MockClient_GetCompanyTickers_Call{Call: _e.mock.On("GetCompanyTickers", ctx)}
}

func (_c *MockClient_GetCompanyTickers_Call) Run(run func(ctx context.Context)) *MockClient_GetCompanyTickers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockClient_GetCompanyTickers_Call) Return(_a0 []sec.CompanyTicker, _a1 error) *MockClient_GetCompanyTickers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetCompanyTickers_Call) RunAndReturn(run func(context.Context) ([]sec.CompanyTicker, error)) *MockClient_GetCompanyTickers_Call {
	_c.Call.Return(run)
	return _c
}

// GetEquityFacts provides a mock function with given fields: ctx, ticker
func (_m *MockClient) GetEquityFacts(ctx context.Context, ticker string) (*sec.EquityFacts, error) {
	ret := _m.Called(ctx, ticker)

	if len(ret) == 0 {
		panic("no return value specified for GetEquityFacts")
	}

	var r0 *sec.EquityFacts
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*sec.EquityFacts, error)); ok {
		return rf(ctx, ticker)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *sec.EquityFacts); ok {
		r0 = rf(ctx, ticker)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sec.EquityFacts)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, ticker)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetEquityFacts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEquityFacts'
type MockClient_GetEquityFacts_Call struct {
	*mock.Call
}

// GetEquityFacts is a helper method to define mock.On call
//   - ctx context.Context
//   - ticker string
func (_e *MockClient_Expecter) GetEquityFacts(ctx interface{}, ticker interface{}) *MockClient_GetEquityFacts_Call {
	return &MockClient_GetEquityFacts_Call{Call: _e.mock.On("GetEquityFacts", ctx, ticker)}
}

func (_c *MockClient_GetEquityFacts_Call) Run(run func(ctx context.Context, ticker string)) *MockClient_GetEquityFacts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClient_GetEquityFacts_Call) Return(_a0 *sec.EquityFacts, _a1 error) *MockClient_GetEquityFacts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetEquityFacts_Call) RunAndReturn(run func(context.Context, string) (*sec.EquityFacts, error)) *MockClient_GetEquityFacts_Call {
	_c.Call.Return(run)
	return _c
}

// ResolveCIK provides a mock function with given fields: ctx, ticker
func (_m *MockClient) ResolveCIK(ctx context.Context, ticker string) (uint64, error) {
	ret := _m.Called(ctx, ticker)

	if len(ret) == 0 {
		panic("no return value specified for ResolveCIK")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (uint64, error)); ok {
		return rf(ctx, ticker)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) uint64); ok {
		r0 = rf(ctx, ticker)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, ticker)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_ResolveCIK_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveCIK'
type MockClient_ResolveCIK_Call struct {
	*mock.Call
}

// ResolveCIK is a helper method to define mock.On call
//   - ctx context.Context
//   - ticker string
func (_e *MockClient_Expecter) ResolveCIK(ctx interface{}, ticker interface{}) *MockClient_ResolveCIK_Call {
	return &MockClient_ResolveCIK_Call{Call: _e.mock.On("ResolveCIK", ctx, ticker)}
}

func (_c *MockClient_ResolveCIK_Call) Run(run func(ctx context.Context, ticker string)) *MockClient_ResolveCIK_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClient_ResolveCIK_Call) Return(_a0 uint64, _a1 error) *MockClient_ResolveCIK_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_ResolveCIK_Call) RunAndReturn(run func(context.Context, string) (uint64, error)) *MockClient_ResolveCIK_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
